### ISSUE TITLE
Kategory brand assets

### ISSUE THREAD

**Issue by israelperezglez** [kategory/kategory#144]
I attach brand assets in PNG and SVG format
[kategory-assets.zip](https://github.com/kategory/kategory/files/1172695/kategory-assets.zip)

**Comment by pakoito** [comment]
Which font does it use?

**Comment by israelperezglez** [comment]
@pakoito We use Fira Mono 
https://fonts.google.com/specimen/Fira+Mono 
;)

**Comment by wiyarmir** [comment]
Should these be added to the repo tree?

**Comment by pakoito** [comment]
unzipped on /assets/ IMO, I don't know the standard @raulraja @JorgeCastilloPrz @ffgiraldez

**Comment by pakoito** [comment]
I'd also include the font on the folder

**Comment by wiyarmir** [comment]
I've seen other projects call this `/art/` since assets could be whatever in a software project. Additionally, this is pure art 😄

**Comment by raulraja** [comment]
We can add the sketch files and all other art into it's own repo so it does not interfere when people just want to clone the main repo size wise. @israelperezglez can you upload all sources and design materials as they become ready to https://github.com/kategory/art ? For work already approved you can just push directly to master which you should have access now. Thanks!

**Comment by pakoito** [comment]
I've added the brand assets, along with info and license for the font, to the art sub-project: https://github.com/kategory/art

Feel free to close this issue anytime.
