### ISSUE TITLE
Is there a Wiki/documentation somewhere?

### ISSUE THREAD

**Issue by asarkar** [kategory/kategory#185]
http://kategory.io is the Git repo

**Comment by ffgiraldez** [comment]
Actually not, we are in an early stage, but it's one of our main goals after releasing a stable version (soon).

For now just reserved the domain and point out to our Github repo.

mean while if you want to know a bit more, Kλtegory it's inspired by Scala [Cats](https://github.com/typelevel/cats) and there you could find how to use it more or less (Kotlin have some limitations and workarounds that Scala don't)

Also, some contributors have repositories with examples of usage.

@Guardiola31337  have UIGestureGen [PR#12](https://github.com/Guardiola31337/uiagesturegen/pull/12) and  [PR#13](https://github.com/Guardiola31337/uiagesturegen/pull/13)

@JorgeCastilloPrz have [Kotlin Android Functional](https://github.com/JorgeCastilloPrz/KotlinAndroidFunctional)

**Comment by asarkar** [comment]
If Kλtegory is inspired by Cats, you'd know that Cats took off because Scalaz attitude to people using the library was "read the code, it's self-documenting".  I guess I'll come back in a year or so.

**Comment by pakoito** [comment]
@asarkar We're building the documentation at the moment, including the Kotlin counterpart to tut: https://github.com/kategory/ank The domain you mention is also being built, and so are the example [libraries](https://github.com/Guardiola31337/uiagesturegen/tree/master/uiagesturegen/src/main/kotlin/com/pguardiola/uigesturegen/dsl) and [apps](https://github.com/JorgeCastilloPrz/KotlinAndroidFunctional). I'll ask you for a bit of patience, as we understand the importance of documentation and have placed people on it already.

**Comment by raulraja** [comment]
@asarkar are you familiar with FP? if so, We'd love if you could help with the docs. Cheers :beers: !

**Comment by asarkar** [comment]
@pakoito Thanks, trust me when I say that I understand it can be difficult to build a framework, and also create documentation for users at the same time. I only wanted to ask if there are any docs, and if not, if you're planning to create some. The answer I got is no, and yes.
@raulraja Yes, I'm familiar with FP, but I'm not convinced that Kotlin is a functional language, or should be shoehorned into behaving like one; I'd rather spend my time on Scala.
