### ISSUE TITLE
Add missing traverse instance for NonEmptyList

### ISSUE THREAD

**Issue by raulraja** [kategory/kategory#202]

**Comment by Atternatt** [comment]
i take this, can you assign me @raulraja ?

**Comment by tonilopezmr** [comment]
https://github.com/kategory/kategory/blob/9e456fa278cd1b5d1398b78a336bc88cabdea653/kategory/src/main/kotlin/kategory/instances/ListKWInstances.kt#L7

and add `TraverseLaws` like this
https://github.com/kategory/kategory/blob/master/kategory/src/test/kotlin/kategory/data/ListKWTest.kt#L19
