### ISSUE TITLE
Deduplicate law tests

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#213]
For some data types and laws we have to run the same tests multiple times. For example, Id has both Monad and Comonad, and each have laws that require testing for Functor. This effectively means the same batch of tests gets run twice.

Deduplication should be simple if the tests are not immediately run, and are instead aggregated in a set where their name string is their identity.

**Comment by pakoito** [comment]
The point where functions should be deduplicated is here: https://github.com/kategory/kategory/blob/9c81e7a0d0964502fbdd748b23169e80f2022c6e/kategory-test/src/main/kotlin/kategory/UnitSpec.kt#L12

Make testLaws take a vararg of List<Law> that removes duplicates based off Law#name: https://github.com/kategory/kategory/blob/9c81e7a0d0964502fbdd748b23169e80f2022c6e/kategory-test/src/main/kotlin/kategory/laws/Law.kt#L5

**Comment by groodt** [comment]
We should be able to close this now?
