### ISSUE TITLE
MonadError instance for Option

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#238]
We need a MonadError instance for Option. You can base the implementation in Either's: https://github.com/kategory/kategory/blob/master/kategory/src/main/kotlin/kategory/instances/EitherInstances.kt#L31-L39 except Either.Left(exception) becomes Option.None

**Comment by victorg1991** [comment]
Me lo pido :D

**Comment by pakoito** [comment]
It's there, just the monadError() call in the companion is missing.

**Comment by pt2121** [comment]
anyone working on this? can i take it?

**Comment by pakoito** [comment]
Sure, go ahead!
