### ISSUE TITLE
Map wrapper and instances

### ISSUE THREAD

**Issue by raulraja** [kategory/kategory#254]
There is `Traverse`, `Semigroup` and `Monoid` instances for `Map` that we should add based on the kotlin std lib map.

Reference:
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/instances/map.scala
https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/map.scala

**Comment by victorg1991** [comment]
Can I take this one? 😇
