### ISSUE TITLE
`Try` Docs

### ISSUE THREAD

**Issue by raulraja** [kategory/kategory#312]

**Comment by ahdezma** [comment]
Si nadie se opone, me lo pido 😛

**Comment by pakoito** [comment]
@ahdezma me gustaría tener Try antes del viernes. Te ves fuerte, o te la mango descaradamente? :D

**Comment by ahdezma** [comment]
Entre hoy y mañana subo un draft de lo que tengo, para que le eches un vistazo :)

**Comment by nomisRev** [comment]
Closed by #458
