### ISSUE TITLE
Bimonad for Eval

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#402]
Implement Bimonad for Eval. The only requirement is to add Bimonad to the @derived clause in Eval.kt, and add the methods extract and coflatmap as done in cats:

https://github.com/typelevel/cats/blob/dab28d71a7a106767fe557f3647ab03d4721466f/core/src/main/scala/cats/Eval.scala#L378-L385

**Comment by aedans** [comment]
[https://github.com/kategory/kategory/pull/409](url)

**Comment by pakoito** [comment]
Thank you very much for your contribution! I see that you've got our version of deriving and laws nailed down first try :D

**Comment by pakoito** [comment]
I've checked your background, you seem quite experienced with this kind of project. Ping us on our gitter (https://gitter.im/kategory/Lobby) if you'd like to chat about internals or work on larger tickets :D
