### ISSUE TITLE
Invalid table markdown in optics docs

### ISSUE THREAD

**Issue by nomisRev** [kategory/kategory#425]
It seems that markdown I used for tables is incorrect.

http://kategory.io/docs/optics/getter/#composition

**Comment by aballano** [comment]
@nomisRev I checked in Github and [it renders fine](https://github.com/kategory/kategory/tree/master/kategory-docs/docs/docs/optics/getter), any idea why should it fail? Do we know what kind of markdown are we using for the page, like, is it different from Github's?

**Comment by NathanQuinn** [comment]
It's rendering the same html in both locations, the difference is just in the css between github and that of the doc site. 

@israelperezglez looking at https://github.com/kategory/kategory/blob/master/kategory-docs/docs/css/kategory.css#L102-L107 seems like you may be the person to discuss modifying this with.

**Comment by raulraja** [comment]
Talked to @israelperezglez , he is gonna help us fix it.

**Comment by nomisRev** [comment]
fixed by #450
