### ISSUE TITLE
Dependency Injection Documentation

### ISSUE THREAD

**Issue by dgoetsch** [kategory/kategory#431]
I've been reading through the kategory documentation.  I found this page for dependency injection:
http://kategory.io/docs/patterns/dependency_injection/

Unfortunately, its still labeled as TODO.  I found the `Inject` interface, but I still haven't figured out how to use it.

I'd be happy to propose some docs and create some examples, but I think that first I need to have a conversation - I'm not familiar with this pattern. I quickly browsed the referenced paper, but I'll be honest it was mostly over my head.

**Comment by pakoito** [comment]
Our current focus is documentation, we've been mostly on feature lockdown for the whole month. Dependency Injection should be available soon, as tracked in (https://github.com/kategory/kategory/issues/360)

Meanwhile, @JorgeCastilloPrz has a good intro to DI with reader monad on Medium: https://medium.com/@JorgeCastilloPr/kotlin-dependency-injection-with-the-reader-monad-7d52f94a482e

**Comment by dgoetsch** [comment]
Thanks @pakoito!
