### ISSUE TITLE
Rename instances of apply to operator invoke

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#459]
In some of the classes ported from cats, like Yoneda and Coyoneda, we're using Scala's apply instead of Kotlin's invoke.

Yoneda: https://github.com/kategory/kategory/search?utf8=%E2%9C%93&q=Yoneda.apply&type=

Coyoneda: https://github.com/kategory/kategory/blob/master/kategory-core/src/main/kotlin/kategory/free/Coyoneda.kt#L26-L28

**Comment by voghDev** [comment]
I'll go with this one
