### ISSUE TITLE
New module: kategory-nullable

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#466]
Based off this gist, it can be proved that null types have the same capabilities as Option, it's just a case of writing the instances.

https://gist.github.com/pakoito/91c01237217483b7be509996b243cf28

The only tricky part is that we cannot provide an isomorphism using subclassing to be used in instances, so a hack may be required:

```kotlin
fun <A> k(a: A?): HK<NullableHK, A> = a as HK<NullableHK, A> // Wouldn't work
```

**Comment by JorgeCastilloPrz** [comment]
But wouldn't we end up creating Option again? Option is already the way to represent explicit nullability with a type.

**Comment by pakoito** [comment]
Yes, after tinkering with it I thought it wouldn't be a good idea.
