### ISSUE TITLE
Examples-based tests

### ISSUE THREAD

**Issue by jmfayard** [kategory/kategory#486]
Hello, 
kategory.io has not yet complete documentation for everything, which is ok since Rome was not built in one day
So I dived into the tests to try to grasp how this works and discovered that you have powerful laws-based testing. But since we learn first by seeing an example and then generalizing, why not combine that with more traditional examples-based unit tests? Those more concrete examples can then serve as a basis for the docs.

My 2 cents=> 
https://gist.github.com/jmfayard/552512b30d2b5771c1c23afd1a593d1b

**Comment by pakoito** [comment]
@jmfayard we'd be happy to add a new module kategory-examples containing such tests, snippets, and larger examples. Would you be willing to become a contributor and add them as you learn more about the lib? I could have a skeleton done for you to start in this week.

**Comment by jmfayard** [comment]
yes! @pakoito

**Comment by pakoito** [comment]
Cool, I'll get on it and update you here :D

**Comment by pakoito** [comment]
PR sent, I'll get it approved ASAP and feel free to start hacking now :D
